#ifndef BIGINT_H_
#define BIGINT_H_

typedef struct{
	int *data;
	int lange;
	int used;
}BIGINT;

void BIGINTREALIGN(BIGINT *INPUT);
void BIGINTPRINT(BIGINT INPUT);
void BIGINTSET(BIGINT *INPUT,long long STARTWERT);
void BIGINTRESET(BIGINT *INPUT,long long STARTWERT);
void BIGINTADDI(BIGINT *INPUT,long long ADDITION);
void BIGINTADDBI(BIGINT *INPUT,BIGINT ADDITION);
void BIGINTPOWER(BIGINT *INPUT,long long POWER);
void BIGINTMLTPY(BIGINT *INPUT,long long FAKTOR);
void BIGINTPRINTF(BIGINT INPUT, FILE* DATEI);
void BIGINTMLTPYPOWER(BIGINT *INPUT,long long FAKTOR);
void BIGINTFACULTY(BIGINT *INPUT, int FACULTY);
int BIGINTDIGITSUM(BIGINT INPUT);
int BIGINTVALUE(BIGINT INPUT);
void BIGINTFREE(BIGINT *INPUT);
void BIGINTREAD(BIGINT *DEST,FILE* DATEI);




#endif
